In [1]:
import numpy as np
npr = lambda x: np.random.randn(*x)
import re

In [30]:
def _relu(x):
    if x>0.: return x

    return 0.

relu = np.vectorize(_relu)

def sigmoid(x):
    return 0.5 * (np.tanh(x / 2) + 1)

In [3]:
def loss(preds, targets):
    #preds = predict(W, b, inputs)
    label_probs = preds * targets + (1 - preds) * (1 - targets)
    return -np.log(label_probs)

In [4]:
X0 = npr((10,11))

W0 = npr((11,2))
B0 = npr((2,))

In [5]:
Y0 = np.matmul(X0,W0)+B0

X1 = relu(Y0)

In [6]:
W1 = npr((2,1))
B1 = npr((1,))

In [7]:
Y1 = np.matmul(X1,W1) + B1

In [13]:
S1 = sigmoid(Y1)
T = np.ones(S1.shape)
L1 = loss(S1,T)

In [9]:
vars = [k for k in locals() if re.match("^[A-Z][0-9]", k) ]
for v in vars:
    print(f"{v}: ")
    print(locals()[v].shape)

X0: 
(10, 11)
W0: 
(11, 2)
B0: 
(2,)
Y0: 
(10, 2)
X1: 
(10, 2)
W1: 
(2, 1)
B1: 
(1,)
Y1: 
(10, 1)
S1: 
(10, 1)
L1: 
(10, 1)


In [10]:
L1

array([[0.84914219],
       [0.67786   ],
       [6.47333578],
       [0.97743349],
       [0.78919186],
       [0.62650186],
       [1.68850463],
       [0.84914219],
       [0.44930255],
       [0.91190638]])

In [17]:
# DL1/DS1
DL1_DS1 = -T/S1 + (1-T)/(1-S1)

# DS1/DY1 
DS1_DY1 = 0.5/(np.cosh(Y1)**2)

In [18]:
DS1_DY1

array([[4.59964047e-01],
       [4.99525620e-01],
       [4.78301887e-06],
       [3.91262071e-01],
       [4.83505282e-01],
       [4.90590682e-01],
       [9.29727328e-02],
       [4.59964047e-01],
       [3.68333303e-01],
       [4.28420922e-01]])

In [74]:
DL1_DY1 = DL1_DS1 * DS1_DY1

In [87]:
DL1_DY1

array([[-1.0752307 ],
       [-0.98389471],
       [-0.00309768],
       [-1.0398285 ],
       [-1.0644932 ],
       [-0.91792161],
       [-0.50311103],
       [-1.0752307 ],
       [-0.57725886],
       [-1.06636671]])

In [88]:
W1.T

array([[-1.19328074,  0.10723971]])

In [79]:
DL1_DX1 = np.matmul(DL1_DY1, W1.T)

In [85]:
DL1_DW1 = np.matmul(X1.T, DL1_DY1)

In [80]:
DL1_DB1 = DL1_DY1

In [81]:
DL1_DY0 = DL1_DX1 * np.sign(X1)

In [82]:
DL1_DW0 = np.matmul(X0.T,DL1_DY0)

In [83]:
vars = [k for k in locals() if re.match("^[A-Z].*_", k) ]
for v in vars:
    print(f"{v}: ")
    print(locals()[v].shape)

DL1_DS1: 
(10, 1)
DS1_DY1: 
(10, 1)
DY1_DX1: 
(1, 2)
DX1_DY0: 
(10, 2)
DY0_DW0: 
(11, 10)
DL1_DW0: 
(11, 2)
DX1_DW0: 
(11, 2)
DY1_DW0: 
(1, 11)
D1L_DX0: 
(10, 11)
DL1_DY1: 
(10, 1)
DL1_DX1: 
(10, 2)
DL1_DB1: 
(10, 1)
DL1_DY0: 
(10, 2)
