In [1]:
import numpy as np


In [4]:
W = np.random.random((3,5))

In [6]:
X = np.random.random((5,7)) # each column is a data vector of 5 elements

In [12]:
Y = np.matmul(W,X)

In [13]:
Y.shape # each column is a data vector of 3 elements

(3, 7)

In [24]:
b = np.ones((3,1)); b[1]=0

In [25]:
b

array([[1.],
       [0.],
       [1.]])

In [26]:
Y+b # b gets added column-wise

array([[2.1629058 , 1.80570549, 2.35698668, 1.77040384, 2.04138546,
        2.74438714, 1.99889648],
       [1.72096189, 1.58718853, 1.88711713, 0.64576737, 1.88964137,
        2.0088652 , 1.81233546],
       [2.61808491, 2.06834307, 2.91855649, 2.01666475, 2.52317438,
        3.03480308, 2.45261408]])

In [27]:
Y

array([[1.1629058 , 0.80570549, 1.35698668, 0.77040384, 1.04138546,
        1.74438714, 0.99889648],
       [1.72096189, 1.58718853, 1.88711713, 0.64576737, 1.88964137,
        2.0088652 , 1.81233546],
       [1.61808491, 1.06834307, 1.91855649, 1.01666475, 1.52317438,
        2.03480308, 1.45261408]])

In [36]:
### so some function that rolls us to one output point per input vecotor would give a 7 element vector
u = np.random.random((1,3))
s= np.matmul(u,Y)

In [37]:
#ds/db = ds/dY * dy/db
u


array([[0.30888573, 0.66733611, 0.87951837]])