In [4]:
import numpy as np
npr = np.random.random

In [7]:
X = npr((10,2))

In [8]:
X

array([[0.26287869, 0.27229263],
       [0.32641664, 0.83941329],
       [0.51956314, 0.54189685],
       [0.31369354, 0.08814412],
       [0.84412969, 0.97669103],
       [0.44878978, 0.22345152],
       [0.26107496, 0.85379466],
       [0.3341591 , 0.45556927],
       [0.6738017 , 0.02884697],
       [0.81643066, 0.06952515]])

In [13]:
W = npr((2,1))
W

array([[0.16748245],
       [0.995335  ]])

In [18]:
b = npr(1)
b

array([0.37483698])

In [16]:
np.matmul(X,W)

array([[0.31504995],
       [0.89016649],
       [0.62638661],
       [0.14027109],
       [1.11351168],
       [0.29757354],
       [0.89353719],
       [0.50940982],
       [0.14156236],
       [0.20593863]])

In [23]:
Y=np.matmul(X,W) + b*np.ones((10,1))
Y

array([[0.68988693],
       [1.26500347],
       [1.00122359],
       [0.51510807],
       [1.48834866],
       [0.67241052],
       [1.26837417],
       [0.8842468 ],
       [0.51639934],
       [0.58077561]])

In [28]:
# dldw[k] += dldy[l]*dyds[l]*dsdwi;
# each row in x (transposed) is dy/dw for that row in y
# 1 is dy/db for that row in y
sum(X)

array([4.80093791, 4.34962548])

In [24]:
W

array([[0.16748245],
       [0.995335  ]])

In [30]:
W0 = npr((11,2))
X0 = npr((10,11))

In [33]:
X = np.matmul(X0,W0)
X

array([[2.27882901, 2.014375  ],
       [2.53711262, 2.67405159],
       [2.88552265, 3.42560621],
       [3.01273565, 3.4425    ],
       [1.68700695, 2.05436226],
       [2.16607869, 1.96967053],
       [3.22643233, 3.3490796 ],
       [3.20694832, 3.05813332],
       [3.25637805, 3.51214737],
       [2.03803476, 2.62323533]])

In [34]:
Y=np.matmul(X,W) + b*np.ones((10,1))
Y

array([[2.76147881],
       [3.46133598],
       [4.26773716],
       [4.30585809],
       [2.70215971],
       [2.69809918],
       [4.24866394],
       [3.9558117 ],
       [4.41598639],
       [3.32716999]])

In [37]:
# dY/dw0 = dy/dX * dX/dw0
display(W) # dy/dx
display(X0) # dx / dw0
# each row in X0 scalar multiplies each element of W here to get the weight update

array([[0.16748245],
       [0.995335  ]])

array([[0.8055881 , 0.00488238, 0.52317917, 0.11309795, 0.38737585,
        0.76248791, 0.69849786, 0.21961957, 0.09706173, 0.17423576,
        0.83618596],
       [0.71060083, 0.02278039, 0.72913805, 0.41775453, 0.37542355,
        0.85427692, 0.7095655 , 0.51346797, 0.3241253 , 0.21857299,
        0.64151293],
       [0.41979138, 0.66619757, 0.67108811, 0.62295625, 0.79503509,
        0.33844447, 0.95033704, 0.45810169, 0.35482643, 0.36198029,
        0.57255385],
       [0.7199008 , 0.99322182, 0.28655013, 0.74415093, 0.27221296,
        0.14434365, 0.49841309, 0.74981321, 0.02282357, 0.46641304,
        0.56302557],
       [0.62960605, 0.36134236, 0.50090449, 0.43288622, 0.10373873,
        0.04997121, 0.40094024, 0.03121893, 0.86711724, 0.62488871,
        0.07064501],
       [0.93849475, 0.04668371, 0.0026064 , 0.05609568, 0.02915662,
        0.57410103, 0.27460708, 0.50088289, 0.76511317, 0.29016871,
        0.7273039 ],
       [0.95917556, 0.30423168, 0.11098123, 0.12671322, 0.

In [41]:
X0.T.shape

(11, 10)

In [42]:
X.shape

(10, 2)

In [43]:
np.matmul(X0.T,X) # dX/DW0

array([[18.87110415, 19.707808  ],
       [11.8842775 , 13.57212327],
       [11.45805173, 12.20363638],
       [ 9.26421326, 10.38603257],
       [11.4406804 , 12.45299092],
       [11.99233489, 12.3630863 ],
       [11.30526894, 12.41337683],
       [15.94553876, 16.74081399],
       [12.18692356, 12.94924134],
       [14.31671593, 15.10890266],
       [12.71196683, 13.18674088]])

In [47]:
np.matmul(X,W0.T).shape # dX/DX0

(10, 11)